import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import { Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700"] });
const cairo = Cairo({ subsets: ["arabic"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-neutral-100`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
